name: onboarding_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.1
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  flutter_local_notifications: ^20.1.0
  hive: ^2.2.3
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  smooth_page_indicator: ^2.0.1
  video_player: ^2.11.0
  geocoding: ^4.0.0
  flutter_timezone: ^5.0.1
  timezone: ^0.10.1
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  go_router: ^15.1.2
  flutter_secure_storage: ^9.2.4
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Images/
    - assets/fonts/
    - assets/videos/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
        - asset: assets/fonts/Oxygen-Bold.ttf
